apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "Missing value DATAFABRIKKEN_INGRESSNAME" .Values.DATAFABRIKKEN_INGRESSNAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ required "Missing value DATAFABRIKKEN_INGRESS_IP_NAME" .Values.DATAFABRIKKEN_INGRESS_IP_NAME }}
spec:
  rules:
  - http:
      paths:
      - path: /veiviser-for-deling-av-data
        pathType: Prefix
        backend:
          service:
            name: datafabrikken-veiviser-dele-data
            port:
              number: 8080
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: datafabrikken-portal-nextjs
            port:
              number: 8080
