name: Deploy to production (ipv4 & ipv6)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-production-ipv4:
    name: Deploy ingress(ipv4) to production environment on merge to master branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@master
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DATAFABRIKKEN_INGRESS_PROD_IPV4 }}

      - name: Apply Helm template
        run: |
          helm repo add datafabrikken-ingress https://datadeling.github.io/helm-chart/
          helm fetch --untar --untardir ./helm datafabrikken-ingress/ingress
          helm template -f ${{ steps.write_file.outputs.filePath }} ./helm/ingress/ > ./kubectlapply.yaml --debug
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DATAFABRIKKEN_PROD_AUTODEPLOY }}
          project_id: datafabrikken-prod
          location_zone: europe-north1-a
          cluster_name: datafabrikken-prod

      - name: Deploy to production
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

  # Consider moving to separate slack-channel
  #      - name: Notify slack
  #        uses: 8398a7/action-slack@v3
  #        with:
  #          mention: 'channel'
  #          if_mention: failure
  #          status: ${{ job.status }}
  #          author_name: 'Application: ingress(ipv4) | Environment: prod'
  #          fields: commit,author,workflow,message
  #        env:
  #          GITHUB_TOKEN: ${{ github.token }}
  #          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #        if: always()

  deploy-production-ipv6:
    name: Deploy ingress(ipv6) to prod environment on merge to master branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@master
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DATAFABRIKKEN_INGRESS_PROD_IPV6 }}

      - name: Apply Helm template
        run: |
          helm repo add datafabrikken-ingress https://datadeling.github.io/helm-chart/
          helm fetch --untar --untardir ./helm datafabrikken-ingress/ingress
          helm template -f ${{ steps.write_file.outputs.filePath }} ./helm/ingress/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DATAFABRIKKEN_PROD_AUTODEPLOY }}
          project_id: datafabrikken-prod
          location_zone: europe-north1-a
          cluster_name: datafabrikken-prod

      - name: Deploy to production
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

# Consider moving to separate slack channel
#      - name: Notify slack
#        uses: 8398a7/action-slack@v3
#        with:
#          mention: 'channel'
#          if_mention: failure
#          status: ${{ job.status }}
#          author_name: 'Application: ingress(ipv6) | Environment: prod'
#          fields: commit,author,workflow,message
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: always()
